import Addidas from "./img/these.svg";
import Lv from "./img/lvl.jpeg";
import l from "./img/airwhite.jpg";
import Channel from "./img/chann.svg";
import Leather from "./img/leat.svg";
import Necklace from "./img/myneck.svg";
import view from "./img/view.png";
import scott from "./img/scott.jpeg";
import retro from "./img/retro.jpeg";
import blackcat from "./img/blackcat.jpeg";
import og from "./img/og.jpeg";
import coolretro from "./img/coolretro.jpeg";
import airretro from "./img/airretro.jpeg";
import chunky from "./img/chunky.jpg";
import inf from "./img/inf.jpeg";
import men from "./img/men.jpg";
import bagpack from "./img/bagpack.jpeg";
import messeng from "./img/blackchannel.jpeg";
import P from "./img/P.jpg";
import whitelv from "./img/whitelv.jpeg";
import diorbag from "./img/diorbag.jpeg";
import femalebag from "./img/femalebag.jpeg";
import mlbbasic from "./img/mlbbasic.jpg";
import la from "./img/la.jpg";
import adj from "./img/adj.jpg";
import mia from "./img/MiamiDolphins.jpg";
import buff from "./img/buff.jpg";
import tote from "./img/tote.jpg";
import teal from "./img/teal chan.jpeg";
import abc from "./img/abc.jpg";
import loafers from "./img/loafers.jpg";
import loafer from "./img/loaf.jpg";
import lo from "./img/lo.jpg";
import suede from "./img/lo.jpg";

const product = [
    {
        id: 1,
        product_name: "Adidas Forum Powerphase",
        price: 350,
        currency: "$",
        thumb: Addidas,
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 2,
        product_name: " Louis Vuitton  Bag",
        price: 250,
        currency: "$",
        thumb: Lv,
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 3,
        product_name: " EWW Men's, Black, One Size",
        price: 250,
        currency: "$",
        thumb: P,
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 4,
        product_name: " Channel Female Bag (mint)",
        price: 250,
        currency: "$",
        thumb: Channel,
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 5,
        product_name: " Classic 26 Carat Diamond Necklace",
        price: 250,
        currency: "$",
        thumb: Necklace,
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 6,
        product_name: "leather sandal",
        price: 250,
        currency: "$",
        thumb: Leather,
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 7,
        product_name: " Jordan 6 Retro High “Black Infrared”",
        price: 250,
        currency: "$",
        thumb: inf,
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 8,
        product_name:
            " Men's Jordan 5 Retro Green Bean SilverGreen Bean-Flint Grey (DM9014 003)",
        price: 250,
        currency: "$",
        thumb: l,
        view: view,
        text: "VIEW PRODUCT",
        category: "Shoes",
        for: "men",
    },

    {
        id: 9,
        product_name: " Classic 26 Carat Diamond Necklace",
        price: 250,
        currency: "$",
        thumb: Leather,
        text: "VIEW",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 10,
        product_name:
            "New Era 950 MLB Basic Team Color SAN Francisco Giants Snapback Cap",
        price: 250,
        currency: "$",
        thumb: mlbbasic,
        category: "Caps",
        for: "men",
        view: view,
        text: "VIEW PRODUCT",
    },

    {
        id: 11,
        product_name: "Travis Scott X Jordan 6 Retro High Olive Green",
        price: 250,
        currency: "$",
        thumb: scott,
        category: "Shoes",
        for: "men",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 12,
        product_name: "Off-White X Jordan 4 Retro “Sail",
        price: 250,
        currency: "$",
        thumb: retro,
        category: "Shoes",
        for: "men",
        view: view,
        text: "VIEW PRODUCT",
    },

    {
        id: 13,
        product_name: "Air Jordan 4 Retro “Black Cat”",
        price: 250,
        currency: "$",
        thumb: blackcat,
        category: "Shoes",
        for: "men",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 14,
        product_name: "Jordan 1 Retro High OG “Handcrafted",
        price: 250,
        currency: "$",
        thumb: og,
        category: "Shoes",
        for: "men",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 15,
        product_name: "KAWS X Jordan 4 Retro Cool Grey",
        price: 250,
        currency: "$",
        thumb: coolretro,
        category: "Shoes",
        for: "men",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 16,
        product_name: "NIKE AIR JORDAN 1 RETRO HIGH HERITAGE",
        price: 250,
        currency: "$",
        thumb: airretro,
        category: "Shoes",
        for: "men",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 17,
        product_name: "Nike Airforce 1 Low Custom Chunky Lace Triple White",
        price: 250,
        currency: "$",
        thumb: chunky,
        category: "Shoes",
        for: "men",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 18,
        product_name: "LV BACKPACK",
        price: 250,
        currency: "$",
        thumb: bagpack,
        category: "Bag",
        for: "women",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 19,
        product_name: "Louis Vuitton Trio Messenger Bag",
        price: 250,
        currency: "$",
        thumb: messeng,
        category: "Bag",
        for: "women",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 20,
        product_name: " lv bag",
        price: 250,
        currency: "$",
        thumb: femalebag,
        category: "Bag",
        for: "women",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 21,
        product_name: "Louis Vuitton Backpack (White)",
        price: 250,
        currency: "$",
        thumb: whitelv,
        category: "Bag",
        for: "women",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 22,
        product_name: "High quality Dior bag",
        price: 250,
        currency: "$",
        thumb: diorbag,
        category: "Bag",
        for: "women",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 23,
        product_name: "Louis Vuitton Female Bag",
        price: 250,
        currency: "$",
        thumb: femalebag,
        category: "Bag",
        for: "women",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 24,
        product_name: " Michael Kors XS Carry All Jet Set Travel Womens Tote",
        price: 250,
        currency: "$",
        thumb: teal,
        category: "Bag",
        for: "women",
        view: view,
        text: "VIEW PRODUCT",
    },

    {
        id: 25,
        product_name: "New Era Men's 70331911",
        price: 250,
        currency: "$",
        thumb: men,
        category: "Caps",
        for: "men",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 26,
        product_name:
            "New Era 950 MLB Basic Team Color SAN Francisco Giants Snapback Cap",
        price: 250,
        currency: "$",
        thumb: mlbbasic,
        category: "Caps",
        for: "men",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 27,
        product_name:
            "New Era Los Angeles Dodgers Adjustable 9Fifty MLB Straight Brim Baseball Cap 950",
        price: 250,
        currency: "$",
        thumb: la,
        category: "Caps",
        for: "men",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 28,
        product_name: "New Era NFL 9FIFTY Basic Adjustable Snapback Hat",
        price: 250,
        currency: "$",
        thumb: adj,
        category: "Caps",
        for: "men",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 29,
        product_name: "Miami dolphins",
        price: 250,
        currency: "$",
        thumb: mia,
        category: "Caps",
        for: "men",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 30,
        product_name: "Buffalo Bills",
        price: 250,
        currency: "$",
        thumb: buff,
        category: "Caps",
        for: "men",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 31,
        product_name: " Michael Kors XS Carry All Jet Set Travel Womens Tote",
        price: 250,
        currency: "$",
        thumb: tote,
        category: "Bag",
        for: "women",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 32,
        product_name:
            "New Era Los Angeles Dodgers Adjustable 9Fifty MLB Straight Brim Baseball Cap 95",
        price: 250,
        currency: "$",
        thumb: abc,
        category: "Caps",
        for: "men",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 33,
        product_name: "Mesh Slip On Air Cushion",
        price: 250,
        currency: "$",
        thumb: loafers,
        category: "shoes",
        for: "women",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 34,
        product_name: "Mesh Slip On Air Cushion loafers",
        price: 250,
        currency: "$",
        thumb: loafer,
        category: "shoes",
        for: "women",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 35,
        product_name: "Mesh Slip On Air Cushion loafer  Bl",
        price: 250,
        currency: "$",
        thumb: lo,
        category: "shoes",
        for: "women",
        view: view,
        text: "VIEW PRODUCT",
    },
    {
        id: 36,
        product_name: "suede",
        price: 250,
        currency: "$",
        thumb: suede,
        category: "shoes",
        for: "women",
        view: view,
        text: "VIEW PRODUCT",
    },
];
export default product;
